name: rounded_text_field
description: Background Text, TextField and TextSpan highlighted with rounded corners
version: 1.0.3
repository: https://github.com/HimaniThakuriOS/rounded_text_field.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
